// class try_catch {
//     public static void main(String[] args) {
//         String str = "test";

//         try {
//             int a = Integer.valueOf(str);
//         } catch (NumberFormatException e) {
//             // 여기서 Exception은 클래스이기 때문에 객체 e를 선언해준 것이다.
//             System.out.println("Error!");
//         }
//     }
// }